Second training run.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,8 +22,17 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt || true
+        pip install -r requirements.txt || true # Remove if dependencies fail to install
 
     - name: Run unittests
       run: |
-        python -m unittest discover -s env/tests -p "*.py"
+        python -m unittest discover -s . -p "test_*.py"
+
+    - name: Install test tools
+      run: |
+        pip install coverage
+
+    - name: Run tests with coverage
+      run: |
+        coverage run -m unittest discover -s env/tests -p "test_*.py"
+        coverage report -m
